server:
  port: 8080

spring:
  application:
    name: notice-server

  config:
    import: sm://

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:3306/fillinv_notification?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${sm://DB_USERNAME}
    password: ${sm://DB_PASSWORD}

  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0

  jpa:
    database: mysql
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}:9094
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        spring.json.trusted.packages: "*"

management:
  endpoints:
    web:
      exposure:
        include: "prometheus,health,info"
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}

firebase:
  project-id: ${FIREBASE_PROJECT_ID:}
  dry-run: ${FIREBASE_DRY_RUN:false}
