ALTER TABLE token_entity
    MODIFY COLUMN token VARCHAR(255) NOT NULL UNIQUE,
    MODIFY COLUMN user_id VARCHAR(255) NOT NULL,
    ADD COLUMN created_at DATETIME(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6);